import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.support': 'Support',
    'nav.login': 'Sign In',
    'nav.getStarted': 'Get Started',
    'nav.partners': 'Partners',
    'nav.admin': 'Admin',
    'nav.dashboard': 'Go to Dashboard',

    // Hero Section
    'hero.badge': 'AI-Powered Business Intelligence',
    'hero.title': 'Expand Your Business into the UK Market',
    'hero.description': 'Get comprehensive analysis of your business with AI-powered insights. Understand your market position, identify opportunities, and make data-driven decisions.',
    'hero.startJourney': 'Start Your Analysis',
    'hero.watchDemo': 'Watch Demo',
    'hero.getComprehensive': 'Get Comprehensive Analysis',
    'hero.tryQuickAnalysis': 'Try Quick Analysis (Free)',
    'hero.mostPopularChoice': 'Most Popular Choice',
    'hero.startComprehensive': 'Start Comprehensive Analysis',
    'hero.comprehensiveTitle': 'Comprehensive UK Market Analysis',
    'hero.comprehensiveDesc': 'Get a full evidence-based assessment of your UK market readiness with actionable insights, verified partner matches, and expert review options.',
    'hero.realMetrics': 'Real Metrics & Validation',
    'hero.realMetricsDesc': 'Research-backed scoring algorithms with Companies House verification',
    'hero.advancedPartner': 'Advanced Partner Matching',
    'hero.advancedPartnerDesc': '85%+ match accuracy with detailed explanations and case studies',
    'hero.expertReview': 'Expert Review Available',
    'hero.expertReviewDesc': 'Request human expert validation and consultation calls',
    'hero.ukRequirements': 'UK-Specific Requirements',
    'hero.ukRequirementsDesc': 'Industry benchmarks and regulatory compliance roadmap',
    'hero.whatYouGet': "What You'll Get:",
    'hero.getItem1': '7 evidence-based category scores with detailed breakdown',
    'hero.getItem2': 'Score influence reports showing which factors affect your score',
    'hero.getItem3': 'Smart partner matches with 5-factor compatibility analysis',
    'hero.getItem4': 'UK market benchmarks and industry-specific regulations',
    'hero.getItem5': 'Actionable roadmap with cost estimates and timelines',
    'hero.getItem6': 'Data quality indicators and methodology transparency',
    'hero.statsLine': '⚡ Analysis completed in minutes • 📊 Used by 100+ businesses • ⭐ 95% satisfaction rate',

    // Features Section
    'features.title': 'Powerful Features for Business Growth',
    'features.subtitle': 'Everything you need to analyze, understand, and grow your business',
    'features.aiScore': 'AI-Powered Analysis',
    'features.aiScoreDesc': 'Advanced artificial intelligence analyzes your business data to provide actionable insights',
    'features.docGenerator': 'Comprehensive Reports',
    'features.docGeneratorDesc': 'Get detailed reports covering market analysis, competitive landscape, and growth opportunities',
    'features.partnerMatching': 'Partner Matching',
    'features.partnerMatchingDesc': 'Connect with verified business partners and service providers tailored to your needs',
    'features.smartRoadmap': 'Smart Roadmap',
    'features.smartRoadmapDesc': 'Get a personalized roadmap with actionable steps to achieve your business goals',

    // How It Works Section
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Get started with your business analysis in three simple steps',
    'howItWorks.step1': 'Share Your Business Info',
    'howItWorks.step1Desc': 'Tell us about your business, goals, and current challenges through our simple form',
    'howItWorks.step2': 'Get Analysis',
    'howItWorks.step2Desc': 'Our AI analyzes your business data and generates comprehensive insights and recommendations',
    'howItWorks.step3': 'Take Action',
    'howItWorks.step3Desc': 'Follow your personalized roadmap and connect with recommended partners to grow your business',

    // CTA Section
    'cta.title': 'Ready to Transform Your Business?',
    'cta.description': 'Join thousands of businesses that have already discovered their growth potential with our AI-powered platform',
    'cta.startAnalysis': 'Start Free Analysis',
    'cta.scheduleConsult': 'Schedule Consultation',
    'cta.leadFormTitle': 'Get Your Comprehensive Market Analysis',
    'cta.leadFormDesc': 'Discover your UK market potential with AI-powered insights and verified partner recommendations',

    // Footer
    'footer.description': 'Empowering businesses with AI-driven insights and strategic guidance for sustainable growth',
    'footer.platform': 'Platform',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.features': 'Features',
    'footer.pricing': 'Pricing',
    'footer.api': 'API',
    'footer.helpCenter': 'Help Center',
    'footer.contact': 'Contact',
    'footer.community': 'Community',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.cookies': 'Cookies',
    'footer.copyright': '© 2024 Converta. All rights reserved.',

    // Guest Analysis Form
    'analysis.form.title': 'Get Your Free AI Business Analysis',
    'analysis.form.subtitle': 'Receive comprehensive insights and recommendations for your business',
    'analysis.form.email': 'Email Address',
    'analysis.form.companyName': 'Company Name',
    'analysis.form.businessDesc': 'Business Description',
    'analysis.form.businessDescPlaceholder': 'Describe your business, products/services, and target market...',
    'analysis.form.industry': 'Industry',
    'analysis.form.selectIndustry': 'Select industry',
    'analysis.form.companySize': 'Company Size',
    'analysis.form.selectSize': 'Select size',
    'analysis.form.websiteUrl': 'Website URL (Optional)',
    'analysis.form.whatYouGet': "What you'll get:",
    'analysis.form.benefit1': 'Comprehensive AI business analysis',
    'analysis.form.benefit2': 'UK market readiness score',
    'analysis.form.benefit3': 'Business recommendations and insights',
    'analysis.form.benefit4': 'Instant results',
    'analysis.form.submit': 'Get Free Analysis',
    'analysis.form.processing': 'Processing Analysis...',
    'analysis.form.required': 'Required Fields Missing',
    'analysis.form.requiredDesc': 'Please fill in all required fields.',
    'analysis.form.sellsGoods': 'Does your business sell physical goods/products?',
    'analysis.form.manufacturingStatus': 'What is your manufacturing status?',
    'analysis.form.manufacturerSelf': 'We manufacture our own products',
    'analysis.form.resellerOnly': 'We source/resell products from other manufacturers',
    'analysis.form.manufacturerBoth': 'We do both - manufacture some and source others',
    'analysis.form.manufacturingHelp': 'This helps us match you with appropriate UK partners',
    'analysis.form.selectManufacturing': 'Select your manufacturing status',

    // New Conditional Questions
    'analysis.form.customerType': 'What is your primary customer type?',
    'analysis.form.customerTypeB2B': 'B2B (Business to Business)',
    'analysis.form.customerTypeB2C': 'B2C (Direct to Consumer)',
    'analysis.form.customerTypeBoth': 'Both B2B and B2C',
    'analysis.form.selectCustomerType': 'Select customer type',
    
    'analysis.form.exportExperience': 'What is your international trade experience?',
    'analysis.form.exportNone': 'First time exporter - no international sales yet',
    'analysis.form.exportEarly': 'Early exporter - less than 2 years international sales',
    'analysis.form.exportExperienced': 'Experienced exporter - 2+ years with multiple markets',
    'analysis.form.exportVeteran': 'Veteran exporter - established international operations',
    'analysis.form.selectExportExperience': 'Select your export experience',
    
    'analysis.form.ukMarketStatus': 'What is your current UK market status?',
    'analysis.form.ukExploring': 'Exploring - no UK activity yet',
    'analysis.form.ukInitial': 'Initial contact - speaking with potential partners/customers',
    'analysis.form.ukActive': 'Active sales - already selling to UK customers',
    'analysis.form.ukEstablished': 'Established presence - UK entity, office, or team',
    'analysis.form.selectUkStatus': 'Select your UK market status',
    
    'analysis.form.teamEnglish': 'Does your team include English-speaking staff?',
    'analysis.form.teamEnglishFluent': 'Yes - fluent English speakers in leadership',
    'analysis.form.teamEnglishSome': 'Yes - some English capability in team',
    'analysis.form.teamEnglishLimited': 'Limited - basic English only',
    'analysis.form.teamEnglishNone': 'No - will need language support',
    'analysis.form.selectTeamEnglish': 'Select team English capability',
    
    'analysis.form.seasonality': 'Is your business seasonal?',
    'analysis.form.seasonalityConsistent': 'Year-round consistent demand',
    'analysis.form.seasonalityModerate': 'Moderate seasonality - some peak periods',
    'analysis.form.seasonalityHigh': 'Highly seasonal - major peaks and troughs',
    'analysis.form.selectSeasonality': 'Select business seasonality',

    'analysis.form.industryRegulatory': 'Industry-specific regulatory status',
    'analysis.form.mhraApproval': 'Do you have UK MHRA approval or CE marking for medical devices?',
    'analysis.form.mhraApproved': 'Yes - approved',
    'analysis.form.mhraInProgress': 'In progress',
    'analysis.form.mhraNotStarted': 'Not yet started',
    'analysis.form.mhraNA': 'Not applicable',
    
    'analysis.form.foodSafety': 'Do you have food safety certifications (HACCP, BRC, SALSA)?',
    'analysis.form.foodHACCP': 'HACCP certified',
    'analysis.form.foodBRC': 'BRC certified',
    'analysis.form.foodSALSA': 'SALSA certified',
    'analysis.form.foodMultiple': 'Multiple certifications',
    'analysis.form.foodNone': 'None yet',
    
    'analysis.form.fcaStatus': 'Are you FCA registered or preparing for registration?',
    'analysis.form.fcaRegistered': 'FCA registered',
    'analysis.form.fcaInProgress': 'Application in progress',
    'analysis.form.fcaPlanning': 'Planning to apply',
    'analysis.form.fcaNA': 'Not applicable',

    // Guest Analysis Page
    'analysis.page.backHome': 'Back to Home',
    'analysis.page.title': 'Get Your AI Business Analysis',
    'analysis.page.subtitle': 'Get comprehensive insights about your UK market readiness and connect with our verified partner directory - completely free.',
    'analysis.page.aiTitle': 'AI-Powered Analysis',
    'analysis.page.aiDesc': 'Advanced algorithms analyze your business for UK market readiness',
    'analysis.page.reportTitle': 'Comprehensive Report',
    'analysis.page.reportDesc': 'Detailed insights, recommendations, and growth opportunities',
    'analysis.page.partnerTitle': 'Partner Access',
    'analysis.page.partnerDesc': 'Connect with verified UK business partners and service providers',

    // Guest Results Page
    'results.complete': 'Analysis Complete!',
    'results.ready': 'Your AI business analysis results are ready.',
    'results.score': 'UK Market Readiness Score',
    'results.limited': 'Limited Analysis',
    'results.upgrade': 'Upgrade for Complete Analysis',
    'results.keyFindings': 'Key Findings',
    'results.recommendations': 'Recommendations',
    'results.riskFactors': 'Risk Factors',
    'results.unlockFull': 'Unlock Your Full Business Potential',
    'results.nextStep': 'Ready to Take the Next Step?',
    'results.createAccount': 'Create an account to save your results, access our partner directory, and get personalized recommendations.',
    'results.upgradePremium': 'Upgrade to Premium',
    'results.downloadReport': 'Download Report',
    'results.downloadSummary': 'Download Summary',
    'results.generating': 'Generating your business analysis...',
    'results.notFound': 'Analysis Not Found',
    'results.notFoundDesc': "We couldn't find your analysis results. Please contact support.",
    'results.returnHome': 'Return Home',

    // Lead Capture Form
    'leadForm.defaultTitle': 'Get Your Free Business Analysis',
    'leadForm.defaultTitleAlt': 'Start Your UK Market Journey',
    'leadForm.defaultDesc': 'Discover your UK market potential with our AI-powered analysis. Get personalized insights and partner recommendations.',
    'leadForm.defaultDescAlt': 'Join hundreds of Turkish businesses successfully expanding to the UK market.',
    'leadForm.incentive': 'Free AI Analysis + Partner Matching Report (Worth £299)',
    'leadForm.fullName': 'Full Name',
    'leadForm.email': 'Email Address',
    'leadForm.phone': 'Phone Number',
    'leadForm.company': 'Company Name',
    'leadForm.industry': 'Industry',
    'leadForm.selectIndustry': 'Select your industry',
    'leadForm.interests': 'Areas of Interest',
    'leadForm.goals': 'Tell us about your goals',
    'leadForm.goalsPlaceholder': 'What are your main objectives for entering the UK market? Any specific challenges you\'re facing?',
    'leadForm.namePlaceholder': 'Your full name',
    'leadForm.emailPlaceholder': 'your.email@company.com',
    'leadForm.phonePlaceholder': '+90 xxx xxx xxxx',
    'leadForm.companyPlaceholder': 'Your company name',
    'leadForm.submit': 'Get My Free Analysis',
    'leadForm.processing': 'Processing...',
    'leadForm.privacy': 'By submitting this form, you agree to receive communications from Converta. We respect your privacy and will never spam you.',
    'leadForm.successTitle': 'Thank you for your interest!',
    'leadForm.successDesc': 'We\'ll be in touch within 24 hours with your personalized business insights.',
    'leadForm.errorTitle': 'Something went wrong',
    'leadForm.errorDesc': 'Please try again or contact our support team.',
    
    // Industries
    'industry.technology': 'Technology',
    'industry.manufacturing': 'Manufacturing',
    'industry.retail': 'Retail & E-commerce',
    'industry.foodBeverage': 'Food & Beverage',
    'industry.textiles': 'Textiles & Fashion',
    'industry.healthcare': 'Healthcare',
    'industry.construction': 'Construction',
    'industry.automotive': 'Automotive',
    'industry.finance': 'Finance',
    'industry.consulting': 'Consulting',
    'industry.other': 'Other',
    
    // Interests
    'interest.ukMarketEntry': 'UK Market Entry',
    'interest.businessAnalysis': 'Business Analysis',
    'interest.partnerMatching': 'Partner Matching',
    'interest.complianceSupport': 'Compliance Support',
    'interest.financialPlanning': 'Financial Planning',
    'interest.digitalMarketing': 'Digital Marketing',

    // Features Page
    'features.badge': 'Comprehensive Business Intelligence Suite',
    'features.heroTitle': 'Every Tool You Need to',
    'features.heroTitleHighlight': 'Grow Your Business',
    'features.heroDesc': 'From AI-powered market analysis to partner matching and compliance tracking, our platform provides everything you need to make informed business decisions and accelerate growth.',
    'features.startAnalysis': 'Start Free Analysis',
    'features.scheduleDemo': 'Schedule Demo',
    'features.scheduling': 'Scheduling...',
    'features.coreTitle': 'Core Features',
    'features.coreSubtitle': 'Powerful tools designed to give you the insights and connections you need to succeed',
    'features.whyChoose': 'Why Choose Converta?',
    'features.whyChooseSubtitle': 'Join thousands of businesses that trust our platform for their growth journey',
    'features.ctaTitle': 'Ready to Transform Your Business?',
    'features.ctaSubtitle': 'Join thousands of businesses that have already discovered their growth potential with our AI-powered platform.',
    
    // Feature Cards
    'features.aiAnalysisTitle': 'AI Business Analysis',
    'features.aiAnalysisDesc': 'Get comprehensive AI-powered analysis of your business performance, market position, and growth opportunities',
    'features.aiAnalysis1': 'Market readiness scoring',
    'features.aiAnalysis2': 'Competitive landscape analysis',
    'features.aiAnalysis3': 'Risk assessment & mitigation',
    'features.aiAnalysis4': 'Growth opportunity identification',
    'features.partnerNetworkTitle': 'Verified Partner Network',
    'features.partnerNetworkDesc': 'Connect with pre-vetted service providers, consultants, and business partners tailored to your needs',
    'features.partnerNetwork1': 'Legal & accounting services',
    'features.partnerNetwork2': 'Marketing & design agencies',
    'features.partnerNetwork3': 'Technology providers',
    'features.partnerNetwork4': 'Logistics & fulfillment',
    'features.complianceTitle': 'Compliance Tracking',
    'features.complianceDesc': 'Stay compliant with automated tracking, document generation, and regulatory guidance',
    'features.compliance1': 'Automated compliance checklists',
    'features.compliance2': 'Document template library',
    'features.compliance3': 'Regulatory change alerts',
    'features.compliance4': 'Expert consultation access',
    'features.roadmapTitle': 'Smart Roadmapping',
    'features.roadmapDesc': 'Get personalized, actionable roadmaps with clear milestones and success metrics',
    'features.roadmap1': 'Goal-oriented planning',
    'features.roadmap2': 'Progress tracking dashboard',
    'features.roadmap3': 'Milestone notifications',
    'features.roadmap4': 'Success metric monitoring',
    'features.analyticsTitle': 'Real-time Analytics',
    'features.analyticsDesc': 'Monitor your business performance with live dashboards and intelligent alerts',
    'features.analytics1': 'Live performance dashboards',
    'features.analytics2': 'Custom KPI tracking',
    'features.analytics3': 'Automated insights & alerts',
    'features.analytics4': 'Exportable reports',
    'features.securityTitle': 'Enterprise Security',
    'features.securityDesc': 'Bank-level security with full data privacy and compliance with international standards',
    'features.security1': 'End-to-end encryption',
    'features.security2': 'GDPR compliance',
    'features.security3': 'SOC 2 Type II certified',
    'features.security4': 'Regular security audits',
    'features.saveTime': 'Save Time & Resources',
    'features.saveTimeDesc': 'Automate complex analysis and get instant insights instead of spending weeks on manual research and planning.',
    'features.expertLevel': 'Expert-Level Insights',
    'features.expertLevelDesc': 'Access the same quality analysis that Fortune 500 companies get, at a fraction of the cost and time.',
    'features.globalScale': 'Global Scalability',
    'features.globalScaleDesc': 'Built for businesses of all sizes, from startups to enterprises, with support for international expansion.',
    
    // Partners Page
    'partners.title': 'Partner Directory',
    'partners.subtitle': 'Connect with verified UK market entry partners',
    'partners.applyPartner': 'Apply as Partner',
    'partners.back': 'Back',
    'partners.verifiedPartners': 'Verified Partners',
    'partners.readyToHelp': 'Ready to help your business',
    'partners.serviceCategories': 'Service Categories',
    'partners.differentSpecializations': 'Different specializations',
    'partners.joinNetwork': 'Join Network',
    'partners.applyNow': 'Apply Now',
    'partners.signInToApply': 'Sign in to apply as a partner',
    'partners.successStories': 'Success Stories',
    'partners.loading': 'Loading partners...',
    'partners.noPartners': 'No verified partners yet',
    'partners.beFirst': 'Be the first to join our partner network and help Turkish SMEs enter the UK market',
    'partners.applicationSubmitted': 'Application Submitted!',
    'partners.applicationDesc': 'Your partner application has been submitted for review.',
    'partners.error': 'Error',
    'partners.failedToLoad': 'Failed to load partners.',

    // Pricing Page
    'pricing.title': 'Pricing Plans',
    'pricing.backToDashboard': 'Back to Dashboard',
    'pricing.manageSubscription': 'Manage Subscription',
    'pricing.partnerDirectory': 'Partner Directory',
    'pricing.customSolution': 'Need a Custom Solution?',
    'pricing.customDesc': "If you're a large organization or need custom features, we'd love to discuss a tailored solution for your needs.",
    'pricing.contactSales': 'Contact Sales',
    'pricing.authRequired': 'Authentication Required',
    'pricing.authRequiredDesc': 'Please sign in to subscribe to a plan.',
    'pricing.errorTitle': 'Error',
    'pricing.subscriptionError': 'Failed to process subscription. Please try again.',
    'pricing.manageError': 'Failed to open subscription management. Please try again.',

    // Access Gate
    'accessGate.title': 'Welcome to Converta MVP',
    'accessGate.description': 'Enter your access code to continue',
    'accessGate.codeLabel': 'Access Code',
    'accessGate.codePlaceholder': 'Enter your access code',
    'accessGate.errorMessage': 'Invalid access code. Please try again.',
    'accessGate.verifying': 'Verifying...',
    'accessGate.submitButton': 'Access Platform',
    'accessGate.accessIncludes': 'What you\'ll get access to:',
    'accessGate.feature1': 'Full platform landing pages and features overview',
    'accessGate.feature2': 'Comprehensive AI business analysis tool',
    'accessGate.feature3': 'Verified UK partner directory',
    'accessGate.feature4': 'Detailed market readiness reports',
    'accessGate.contactNote': 'Need an access code? Contact the Converta team.',

    // Auth Page
    'auth.welcome': 'Welcome to Converta',
    'auth.subtitle': 'Sign in or create an account to start your UK market journey',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.passwordHint': 'Password must be at least 6 characters',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.createAccount': 'Create Account',
    'auth.backToHome': 'Back to Home',
    'auth.error': 'Error',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.emailNotConfirmed': 'Please confirm your email first',
    'auth.signInFailed': 'Sign In Failed',
    'auth.signUpFailed': 'Sign Up Failed',
    'auth.userExists': 'An account with this email already exists',
    'auth.welcomeBack': 'Welcome Back!',
    'auth.signInSuccess': 'You have successfully signed in',
    'auth.accountCreated': 'Account Created!',
    'auth.checkEmail': 'Please check your email for confirmation link',
    'auth.disclaimer': 'By continuing, you agree to our Terms of Service and Privacy Policy.',
    'auth.signOut': 'Sign Out',

    // Comprehensive Analysis Form
    'compForm.title': 'Comprehensive Business Analysis',
    'compForm.subtitle': 'Get your complete 7-category assessment with AI-powered insights and partner matching',
    'compForm.step': 'Step',
    'compForm.of': 'of',
    'compForm.back': 'Back',
    'compForm.next': 'Next',
    'compForm.complete': 'Complete',
    'compForm.step1Title': 'Company Information',
    'compForm.step1Desc': 'Tell us about your business',
    'compForm.step2Title': 'Market & Digital Presence',
    'compForm.step2Desc': 'Tell us about your current market reach',
    'compForm.step3Title': 'Compliance & Certifications',
    'compForm.step3Desc': 'Help us understand your regulatory position',
    'compForm.step4Title': 'Goals & Timeline',
    'compForm.step4Desc': 'Tell us about your expansion plans',
    'compForm.companyName': 'Company Name',
    'compForm.industry': 'Industry',
    'compForm.selectIndustry': 'Select your industry',
    'compForm.companySize': 'Company Size',
    'compForm.selectSize': 'Select company size',
    'compForm.yearEstablished': 'Year Established',
    'compForm.websiteUrl': 'Website URL',
    'compForm.businessDesc': 'Business Description',
    'compForm.businessDescPlaceholder': 'Describe what your business does, your main products/services, and what makes you unique',
    'compForm.productsServices': 'Products/Services',
    'compForm.productsPlaceholder': 'Describe your main products or services in detail',
    'compForm.currentMarkets': 'Current Markets',
    'compForm.annualRevenue': 'Annual Revenue',
    'compForm.selectRevenue': 'Select revenue range',
    'compForm.digitalPresence': 'Digital Presence',
    'compForm.hasOnlineStore': 'We have an online store',
    'compForm.hasEcommerce': 'We use e-commerce platforms (Shopify, WooCommerce, etc.)',
    'compForm.hasEnglishWebsite': 'Our website is available in English',
    'compForm.regulatoryCompliance': 'Regulatory Compliance Experience',
    'compForm.qualityCerts': 'Quality Certifications',
    'compForm.targetRegions': 'Target Expansion Regions',
    'compForm.businessGoals': 'Business Goals',
    'compForm.goalsPlaceholder': 'What are your main goals for business expansion? What do you hope to achieve?',
    'compForm.timeline': 'Expansion Timeline',
    'compForm.selectTimeline': 'Select your timeline',
    'compForm.budget': 'Investment Budget',
    'compForm.selectBudget': 'Select budget range',
    'compForm.submitted': 'Information Submitted!',
    'compForm.processing': 'Processing your comprehensive analysis...',
    'compForm.companyNamePlaceholder': 'Enter your company name',
    'compForm.websitePlaceholder': 'https://www.yourcompany.com',
    'compForm.yearPlaceholder': '2020',
    // Industry options
    'compForm.industryTechnology': 'Technology',
    'compForm.industryHealthcare': 'Healthcare',
    'compForm.industryRetail': 'Retail',
    'compForm.industryManufacturing': 'Manufacturing',
    'compForm.industryServices': 'Services',
    'compForm.industryFoodBeverage': 'Food & Beverage',
    'compForm.industryConstruction': 'Construction',
    'compForm.industryAutomotive': 'Automotive',
    'compForm.industryOther': 'Other',
    // Company size options
    'compForm.size1to10': '1-10 employees',
    'compForm.size11to50': '11-50 employees',
    'compForm.size51to200': '51-200 employees',
    'compForm.size200plus': '200+ employees',
    // Revenue options
    'compForm.revenue0to50k': '$0 - $50k',
    'compForm.revenue50to250k': '$50k - $250k',
    'compForm.revenue250to1m': '$250k - $1M',
    'compForm.revenue1to5m': '$1M - $5M',
    'compForm.revenue5mplus': '$5M+',
    // Market options
    'compForm.marketDomestic': 'Domestic',
    'compForm.marketEurope': 'Europe',
    'compForm.marketNorthAmerica': 'North America',
    'compForm.marketAsia': 'Asia',
    'compForm.marketMiddleEast': 'Middle East',
    'compForm.marketOther': 'Other',
    // Digital presence options
    'compForm.digitalWebsite': 'Website',
    'compForm.digitalSocialMedia': 'Social Media',
    'compForm.digitalEcommerce': 'E-commerce',
    'compForm.digitalMobileApp': 'Mobile App',
    'compForm.digitalEmailMarketing': 'Email Marketing',
    'compForm.digitalAdvertising': 'Digital Advertising',
    // Compliance options
    'compForm.complianceISO': 'ISO Standards',
    'compForm.complianceCE': 'CE Marking',
    'compForm.complianceFDA': 'FDA Approval',
    'compForm.complianceGDPR': 'GDPR Compliance',
    'compForm.complianceExport': 'Export Licensing',
    'compForm.complianceQuality': 'Quality Systems',
    // Certification options
    'compForm.certISO9001': 'ISO 9001',
    'compForm.certISO14001': 'ISO 14001',
    'compForm.certOHSAS': 'OHSAS 18001',
    'compForm.certOrganic': 'Organic Certification',
    'compForm.certFairTrade': 'Fair Trade',
    'compForm.certIndustry': 'Industry Specific',
    // Region options
    'compForm.regionUK': 'UK',
    'compForm.regionEurope': 'Europe',
    'compForm.regionNorthAmerica': 'North America',
    'compForm.regionAsiaPacific': 'Asia Pacific',
    'compForm.regionMiddleEast': 'Middle East',
    'compForm.regionGlobal': 'Global',
    // Timeline options
    'compForm.timeline3to6': '3-6 months',
    'compForm.timeline6to12': '6-12 months',
    'compForm.timeline1to2': '1-2 years',
    'compForm.timeline2plus': '2+ years',
    // Budget options
    'compForm.budget0to10k': '$0 - $10k',
    'compForm.budget10to50k': '$10k - $50k',
    'compForm.budget50to100k': '$50k - $100k',
    'compForm.budget100kplus': '$100k+',

    // Comprehensive Analysis Results
    'compResults.title': 'Comprehensive Business Analysis',
    'compResults.loading': 'Processing Your Comprehensive Analysis',
    'compResults.loadingDesc': 'This may take 30-60 seconds...',
    'compResults.failed': 'Analysis Failed',
    'compResults.failedDesc': "We couldn't process your comprehensive analysis. Please try again.",
    'compResults.noData': 'No Business Data',
    'compResults.noDataDesc': 'Please complete the comprehensive analysis form first.',
    'compResults.returnHome': 'Return Home',
    'compResults.exportReport': 'Export Report',
    'compResults.backHome': 'Back to Home',
    'compResults.ukReadiness': 'UK Market Readiness',
    'compResults.confidenceHigh': 'HIGH',
    'compResults.confidenceMedium': 'MEDIUM',
    'compResults.confidenceLow': 'LOW',
    'compResults.dataCompleteness': 'Data Completeness',
    'compResults.fieldsIncomplete': 'fields incomplete',
    'compResults.companiesHouseVerified': 'Companies House Verified',
    'compResults.completedSections': 'Completed sections:',
    'compResults.dataSources': 'Data sources:',
    'compResults.about': 'About',
    'compResults.specialties': 'Specialties',
    'compResults.contactInfo': 'Contact Information',
    'compResults.email': 'Email',
    'compResults.phone': 'Phone',
    'compResults.website': 'Website',
    'compResults.location': 'Location',
    'compResults.noContactInfo': 'No contact information available',
    'compResults.sendEmail': 'Send Email',
    'compResults.close': 'Close',
    'compResults.contactPartner': 'Contact Partner',
    'compResults.scoreBreakdown': 'Score Breakdown',
    'compResults.recommendations': 'Recommendations',
    'compResults.immediate': 'Immediate',
    'compResults.shortTerm': 'Short Term',
    'compResults.longTerm': 'Long Term',
    'compResults.compliance': 'Compliance Assessment',
    'compResults.criticalReq': 'Critical Requirements',
    'compResults.riskAreas': 'Risk Areas',
    'compResults.partners': 'Partner Recommendations',
    'compResults.urgency': 'Urgency',
    'compResults.high': 'High',
    'compResults.medium': 'Medium',
    'compResults.low': 'Low',
    'compResults.disclaimer': 'This analysis is AI-generated and provided for informational purposes only. It does not constitute legal, financial, or professional advice.',
    'compResults.methodology': 'Analysis Methodology & Data Quality',
    'compResults.methodologyDesc': 'Understanding how your score was calculated and data sources used',
    'compResults.confidenceLevel': 'Confidence Level',
    'compResults.verificationStatus': 'Verification Status',
    'compResults.verified': 'VERIFIED',
    'compResults.unverified': 'UNVERIFIED',
    'compResults.verifiedVia': 'Company verified via Companies House API',
    'compResults.notVerified': 'Company not verified - UK registration recommended',
    'compResults.scoringMethod': 'Scoring Methodology',
    'compResults.dataSourcesUsed': 'Data Sources Used:',
    'compResults.improveAccuracy': 'Improve Analysis Accuracy',
    'compResults.provideMore': 'Provide additional information to increase data completeness and confidence:',
    'compResults.expertRecommended': 'Expert Review Recommended',
    'compResults.getExpertReview': 'Get Expert Review',
    'compResults.requestExpert': 'Request Expert Review',
    'compResults.shareResults': 'Share Results',
    'compResults.viewProgress': 'View Progress History',
    'compResults.overview': 'Overview',
    'compResults.insights': 'Insights',
    'compResults.roadmap': 'Roadmap',
    'compResults.detailedBreakdown': 'Detailed Score Breakdown',
    'compResults.categoriesAnalyzed': 'Categories Analyzed',
    'compResults.evidenceBased': 'Evidence-based analysis using proprietary scoring algorithms',
    'compResults.highReadiness': 'High Readiness',
    'compResults.moderateReadiness': 'Moderate Readiness',
    'compResults.needsDevelopment': 'Needs Development',

    // Score Categories
    'scoreCategory.productMarketFit': 'Product-Market Fit',
    'scoreCategory.productMarketFitDesc': 'UK market demand and competition analysis',
    'scoreCategory.regulatoryCompatibility': 'Regulatory Compatibility',
    'scoreCategory.regulatoryCompatibilityDesc': 'UK compliance and legal requirements',
    'scoreCategory.digitalReadiness': 'Digital Readiness',
    'scoreCategory.digitalReadinessDesc': 'Online presence and e-commerce capability',
    'scoreCategory.logisticsPotential': 'Logistics Potential',
    'scoreCategory.logisticsPotentialDesc': 'Supply chain and fulfillment readiness',
    'scoreCategory.scalabilityAutomation': 'Scalability & Automation',
    'scoreCategory.scalabilityAutomationDesc': 'Growth potential and operational efficiency',
    'scoreCategory.founderTeamStrength': 'Founder/Team Strength',
    'scoreCategory.founderTeamStrengthDesc': 'Experience and UK market knowledge',
    'scoreCategory.investmentReadiness': 'Investment Readiness',
    'scoreCategory.investmentReadinessDesc': 'Financial preparedness for UK expansion',

    // Admin Page
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Converta Management Console',
    'admin.backToSite': 'Back to Site',
    'admin.systemHealth': 'System Health',
    'admin.overview': 'Overview',
    'admin.analytics': 'Analytics',
    'admin.users': 'Users',
    'admin.partners': 'Partners',
    'admin.performance': 'Performance',
    'admin.marketing': 'Marketing',
    'admin.totalUsers': 'Total Users',
    'admin.activeUsers': 'Active Users',
    'admin.pendingPartners': 'Pending Partners',
    'admin.conversionRate': 'Conversion Rate',
    'admin.quickActions': 'Quick Actions',
    'admin.quickActionsDesc': 'Common administrative tasks and shortcuts',
    'admin.reviewPartners': 'Review Partners',
    'admin.applicationsPending': 'applications pending',
    'admin.userManagement': 'User Management',
    'admin.manageAccounts': 'Manage user accounts and activity',
    'admin.viewAnalytics': 'View Analytics',
    'admin.platformInsights': 'Platform performance insights',
    'admin.recentActivity': 'Recent Activity',
    'admin.recentActivityDesc': 'Latest platform events and user interactions',
    'admin.loading': 'Loading...',
    'admin.verifyingAccess': 'Verifying access...',
    'admin.authRequired': 'Authentication Required',
    'admin.authRequiredDesc': 'Please log in to access the admin dashboard.',
    'admin.accessDenied': 'Access Denied',
    'admin.accessDeniedDesc': 'You don\'t have permission to access this page.',
    'admin.aboveAverage': 'Above industry average',
    'admin.fromLastMonth': 'from last month',
    'admin.activeRate': 'active rate',
    'admin.totalAnalyses': 'Total Analyses',
  },
  tr: {
    // Header
    'nav.features': 'Özellikler',
    'nav.pricing': 'Fiyatlandırma',
    'nav.support': 'Destek',
    'nav.login': 'Giriş Yap',
    'nav.getStarted': 'Başlayın',
    'nav.partners': 'Ortaklar',
    'nav.admin': 'Yönetici',
    'nav.dashboard': 'Kontrol Paneline Git',

    // Hero Section
    'hero.badge': 'AI Destekli İş Zekası',
    'hero.title': 'İşinizi İngiltere Pazarına Genişletin',
    'hero.description': 'AI destekli içgörülerle işinizin kapsamlı analizini alın. Pazar konumunuzu anlayın, fırsatları belirleyin ve veriye dayalı kararlar alın.',
    'hero.startJourney': 'Analizinizi Başlatın',
    'hero.watchDemo': 'Demo İzleyin',
    'hero.getComprehensive': 'Kapsamlı Analiz Al',
    'hero.tryQuickAnalysis': 'Hızlı Analiz Dene (Ücretsiz)',
    'hero.mostPopularChoice': 'En Popüler Seçim',
    'hero.startComprehensive': 'Kapsamlı Analizi Başlat',
    'hero.comprehensiveTitle': 'Kapsamlı İngiltere Pazar Analizi',
    'hero.comprehensiveDesc': 'Uygulanabilir içgörüler, doğrulanmış ortak eşleşmeleri ve uzman inceleme seçenekleriyle İngiltere pazar hazırlığınızın tam kanıta dayalı değerlendirmesini alın.',
    'hero.realMetrics': 'Gerçek Metrikler ve Doğrulama',
    'hero.realMetricsDesc': 'Companies House doğrulaması ile araştırmaya dayalı puanlama algoritmaları',
    'hero.advancedPartner': 'Gelişmiş Ortak Eşleştirme',
    'hero.advancedPartnerDesc': 'Ayrıntılı açıklamalar ve vaka çalışmalarıyla %85+ eşleşme doğruluğu',
    'hero.expertReview': 'Uzman İncelemesi Mevcut',
    'hero.expertReviewDesc': 'İnsan uzman doğrulaması ve danışmanlık görüşmeleri talep edin',
    'hero.ukRequirements': 'İngiltere\'ye Özel Gereksinimler',
    'hero.ukRequirementsDesc': 'Sektör kıyaslamaları ve mevzuat uyumluluk yol haritası',
    'hero.whatYouGet': 'Ne Alacaksınız:',
    'hero.getItem1': 'Ayrıntılı döküm ile 7 kanıta dayalı kategori puanı',
    'hero.getItem2': 'Hangi faktörlerin puanınızı etkilediğini gösteren puan etki raporları',
    'hero.getItem3': '5 faktörlü uyumluluk analizi ile akıllı ortak eşleşmeleri',
    'hero.getItem4': 'İngiltere pazar kıyaslamaları ve sektöre özel düzenlemeler',
    'hero.getItem5': 'Maliyet tahminleri ve zaman çizelgeleri ile uygulanabilir yol haritası',
    'hero.getItem6': 'Veri kalitesi göstergeleri ve metodoloji şeffaflığı',
    'hero.statsLine': '⚡ Dakikalar içinde analiz tamamlanır • 📊 100+ işletme tarafından kullanılıyor • ⭐ %95 memnuniyet oranı',

    // Features Section
    'features.title': 'İş Büyümesi İçin Güçlü Özellikler',
    'features.subtitle': 'İşinizi analiz etmek, anlamak ve büyütmek için ihtiyacınız olan her şey',
    'features.aiScore': 'AI Destekli Analiz',
    'features.aiScoreDesc': 'Gelişmiş yapay zeka, iş verilerinizi analiz ederek eylem odaklı içgörüler sağlar',
    'features.docGenerator': 'Kapsamlı Raporlar',
    'features.docGeneratorDesc': 'Pazar analizi, rekabet ortamı ve büyüme fırsatlarını kapsayan detaylı raporlar alın',
    'features.partnerMatching': 'Partner Eşleştirme',
    'features.partnerMatchingDesc': 'İhtiyaçlarınıza özel doğrulanmış iş ortakları ve hizmet sağlayıcılarıyla bağlantı kurun',
    'features.smartRoadmap': 'Akıllı Yol Haritası',
    'features.smartRoadmapDesc': 'İş hedeflerinize ulaşmak için eylem odaklı adımlarla kişiselleştirilmiş yol haritası alın',

    // How It Works Section
    'howItWorks.title': 'Nasıl Çalışır',
    'howItWorks.subtitle': 'Üç basit adımda iş analizinizi başlatın',
    'howItWorks.step1': 'İş Bilgilerinizi Paylaşın',
    'howItWorks.step1Desc': 'Basit formumuz aracılığıyla işiniz, hedefleriniz ve mevcut zorluklarınız hakkında bize bilgi verin',
    'howItWorks.step2': 'Analizi Alın',
    'howItWorks.step2Desc': 'AI\'mız iş verilerinizi analiz eder ve kapsamlı içgörüler ve öneriler üretir',
    'howItWorks.step3': 'Harekete Geçin',
    'howItWorks.step3Desc': 'Kişiselleştirilmiş yol haritanızı takip edin ve işinizi büyütmek için önerilen ortaklarla bağlantı kurun',

    // CTA Section
    'cta.title': 'İşinizi Dönüştürmeye Hazır mısınız?',
    'cta.description': 'AI destekli platformumuzla büyüme potansiyellerini keşfetmiş binlerce işletmeye katılın',
    'cta.startAnalysis': 'Ücretsiz Analiz Başlatın',
    'cta.scheduleConsult': 'Konsültasyon Planlayın',
    'cta.leadFormTitle': 'Kapsamlı Pazar Analizinizi Alın',
    'cta.leadFormDesc': 'AI destekli içgörüler ve doğrulanmış partner önerileriyle UK pazar potansiyelinizi keşfedin',

    // Footer
    'footer.description': 'İşletmeleri AI destekli içgörüler ve stratejik rehberlikle sürdürülebilir büyüme için güçlendiriyoruz',
    'footer.platform': 'Platform',
    'footer.support': 'Destek',
    'footer.legal': 'Yasal',
    'footer.features': 'Özellikler',
    'footer.pricing': 'Fiyatlandırma',
    'footer.api': 'API',
    'footer.helpCenter': 'Yardım Merkezi',
    'footer.contact': 'İletişim',
    'footer.community': 'Topluluk',
    'footer.privacy': 'Gizlilik',
    'footer.terms': 'Şartlar',
    'footer.cookies': 'Çerezler',
    'footer.copyright': '© 2024 Converta. Tüm hakları saklıdır.',

    // Guest Analysis Form
    'analysis.form.title': 'Ücretsiz AI İş Analizinizi Alın',
    'analysis.form.subtitle': 'İşiniz için kapsamlı içgörüler ve öneriler alın',
    'analysis.form.email': 'E-posta Adresi',
    'analysis.form.companyName': 'Şirket Adı',
    'analysis.form.businessDesc': 'İş Tanımı',
    'analysis.form.businessDescPlaceholder': 'İşinizi, ürünlerinizi/hizmetlerinizi ve hedef pazarınızı açıklayın...',
    'analysis.form.industry': 'Sektör',
    'analysis.form.selectIndustry': 'Sektör seçin',
    'analysis.form.companySize': 'Şirket Büyüklüğü',
    'analysis.form.selectSize': 'Büyüklük seçin',
    'analysis.form.websiteUrl': 'Web Sitesi URL (İsteğe Bağlı)',
    'analysis.form.whatYouGet': 'Neler alacaksınız:',
    'analysis.form.benefit1': 'Kapsamlı AI iş analizi',
    'analysis.form.benefit2': 'UK pazar hazırlık skoru',
    'analysis.form.benefit3': 'İş önerileri ve içgörüler',
    'analysis.form.benefit4': 'Anında sonuçlar',
    'analysis.form.submit': 'Ücretsiz Analiz Al',
    'analysis.form.processing': 'Analiz İşleniyor...',
    'analysis.form.required': 'Gerekli Alanlar Eksik',
    'analysis.form.requiredDesc': 'Lütfen tüm gerekli alanları doldurun.',
    'analysis.form.sellsGoods': 'İşletmeniz fiziksel ürün satıyor mu?',
    'analysis.form.manufacturingStatus': 'Üretim durumunuz nedir?',
    'analysis.form.manufacturerSelf': 'Ürünlerimizi kendimiz üretiyoruz',
    'analysis.form.resellerOnly': 'Diğer üreticilerden ürün tedarik ediyoruz',
    'analysis.form.manufacturerBoth': 'Her ikisi - bazı ürünleri üretiyoruz, bazılarını tedarik ediyoruz',
    'analysis.form.manufacturingHelp': 'Bu, sizi uygun İngiltere ortaklarıyla eşleştirmemize yardımcı olur',
    'analysis.form.selectManufacturing': 'Üretim durumunuzu seçin',

    // New Conditional Questions
    'analysis.form.customerType': 'Birincil müşteri tipiniz nedir?',
    'analysis.form.customerTypeB2B': 'B2B (İşletmeden İşletmeye)',
    'analysis.form.customerTypeB2C': 'B2C (Doğrudan Tüketiciye)',
    'analysis.form.customerTypeBoth': 'Hem B2B hem B2C',
    'analysis.form.selectCustomerType': 'Müşteri tipini seçin',
    
    'analysis.form.exportExperience': 'Uluslararası ticaret deneyiminiz nedir?',
    'analysis.form.exportNone': 'İlk kez ihracatçı - henüz uluslararası satış yok',
    'analysis.form.exportEarly': 'Erken ihracatçı - 2 yıldan az uluslararası satış',
    'analysis.form.exportExperienced': 'Deneyimli ihracatçı - birden fazla pazarda 2+ yıl',
    'analysis.form.exportVeteran': 'Kıdemli ihracatçı - yerleşik uluslararası operasyonlar',
    'analysis.form.selectExportExperience': 'İhracat deneyiminizi seçin',
    
    'analysis.form.ukMarketStatus': 'Mevcut UK pazar durumunuz nedir?',
    'analysis.form.ukExploring': 'Keşfediyor - henüz UK faaliyeti yok',
    'analysis.form.ukInitial': 'İlk temas - potansiyel ortaklar/müşterilerle görüşüyor',
    'analysis.form.ukActive': 'Aktif satışlar - UK müşterilerine satış yapıyor',
    'analysis.form.ukEstablished': 'Yerleşik varlık - UK şirketi, ofisi veya ekibi var',
    'analysis.form.selectUkStatus': 'UK pazar durumunuzu seçin',
    
    'analysis.form.teamEnglish': 'Ekibinizde İngilizce konuşan personel var mı?',
    'analysis.form.teamEnglishFluent': 'Evet - liderlikte akıcı İngilizce konuşanlar var',
    'analysis.form.teamEnglishSome': 'Evet - ekipte biraz İngilizce kapasitesi var',
    'analysis.form.teamEnglishLimited': 'Sınırlı - sadece temel İngilizce',
    'analysis.form.teamEnglishNone': 'Hayır - dil desteğine ihtiyaç olacak',
    'analysis.form.selectTeamEnglish': 'Ekip İngilizce kapasitesini seçin',
    
    'analysis.form.seasonality': 'İşletmeniz mevsimsel mi?',
    'analysis.form.seasonalityConsistent': 'Yıl boyunca tutarlı talep',
    'analysis.form.seasonalityModerate': 'Orta mevsimsellik - bazı yoğun dönemler',
    'analysis.form.seasonalityHigh': 'Yüksek mevsimsellik - büyük iniş çıkışlar',
    'analysis.form.selectSeasonality': 'İşletme mevsimselliğini seçin',

    'analysis.form.industryRegulatory': 'Sektöre özel düzenleyici durum',
    'analysis.form.mhraApproval': 'Tıbbi cihazlar için UK MHRA onayı veya CE işareti var mı?',
    'analysis.form.mhraApproved': 'Evet - onaylı',
    'analysis.form.mhraInProgress': 'Süreçte',
    'analysis.form.mhraNotStarted': 'Henüz başlamadı',
    'analysis.form.mhraNA': 'Uygulanmaz',
    
    'analysis.form.foodSafety': 'Gıda güvenliği sertifikalarınız var mı (HACCP, BRC, SALSA)?',
    'analysis.form.foodHACCP': 'HACCP sertifikalı',
    'analysis.form.foodBRC': 'BRC sertifikalı',
    'analysis.form.foodSALSA': 'SALSA sertifikalı',
    'analysis.form.foodMultiple': 'Birden fazla sertifika',
    'analysis.form.foodNone': 'Henüz yok',
    
    'analysis.form.fcaStatus': 'FCA kayıtlı mısınız veya kayıt için hazırlanıyor musunuz?',
    'analysis.form.fcaRegistered': 'FCA kayıtlı',
    'analysis.form.fcaInProgress': 'Başvuru sürecinde',
    'analysis.form.fcaPlanning': 'Başvurmayı planlıyor',
    'analysis.form.fcaNA': 'Uygulanmaz',

    // Guest Analysis Page
    'analysis.page.backHome': 'Ana Sayfaya Dön',
    'analysis.page.title': 'AI İş Analizinizi Alın',
    'analysis.page.subtitle': 'UK pazar hazırlığınız hakkında kapsamlı içgörüler alın ve doğrulanmış partner dizinimize bağlanın - tamamen ücretsiz.',
    'analysis.page.aiTitle': 'AI Destekli Analiz',
    'analysis.page.aiDesc': 'Gelişmiş algoritmalar işinizi UK pazar hazırlığı için analiz eder',
    'analysis.page.reportTitle': 'Kapsamlı Rapor',
    'analysis.page.reportDesc': 'Detaylı içgörüler, öneriler ve büyüme fırsatları',
    'analysis.page.partnerTitle': 'Partner Erişimi',
    'analysis.page.partnerDesc': 'Doğrulanmış UK iş ortakları ve hizmet sağlayıcılarıyla bağlantı kurun',

    // Guest Results Page
    'results.complete': 'Analiz Tamamlandı!',
    'results.ready': 'AI iş analizi sonuçlarınız hazır.',
    'results.score': 'UK Pazar Hazırlık Skoru',
    'results.limited': 'Sınırlı Analiz',
    'results.upgrade': 'Tam Analiz İçin Yükselt',
    'results.keyFindings': 'Önemli Bulgular',
    'results.recommendations': 'Öneriler',
    'results.riskFactors': 'Risk Faktörleri',
    'results.unlockFull': 'İşinizin Tam Potansiyelini Açın',
    'results.nextStep': 'Bir Sonraki Adıma Hazır mısınız?',
    'results.createAccount': 'Sonuçlarınızı kaydetmek, partner dizinimize erişmek ve kişiselleştirilmiş öneriler almak için bir hesap oluşturun.',
    'results.upgradePremium': 'Premium\'a Yükselt',
    'results.downloadReport': 'Raporu İndir',
    'results.downloadSummary': 'Özeti İndir',
    'results.generating': 'İş analiziniz oluşturuluyor...',
    'results.notFound': 'Analiz Bulunamadı',
    'results.notFoundDesc': 'Analiz sonuçlarınızı bulamadık. Lütfen destekle iletişime geçin.',
    'results.returnHome': 'Ana Sayfaya Dön',

    // Lead Capture Form
    'leadForm.defaultTitle': 'Ücretsiz İş Analizinizi Alın',
    'leadForm.defaultTitleAlt': 'UK Pazar Yolculuğunuza Başlayın',
    'leadForm.defaultDesc': 'AI destekli analizimizle UK pazar potansiyelinizi keşfedin. Kişiselleştirilmiş içgörüler ve partner önerileri alın.',
    'leadForm.defaultDescAlt': 'UK pazarına başarıyla genişleyen yüzlerce Türk işletmesine katılın.',
    'leadForm.incentive': 'Ücretsiz AI Analizi + Partner Eşleştirme Raporu (299£ Değerinde)',
    'leadForm.fullName': 'Ad Soyad',
    'leadForm.email': 'E-posta Adresi',
    'leadForm.phone': 'Telefon Numarası',
    'leadForm.company': 'Şirket Adı',
    'leadForm.industry': 'Sektör',
    'leadForm.selectIndustry': 'Sektörünüzü seçin',
    'leadForm.interests': 'İlgi Alanları',
    'leadForm.goals': 'Hedefleriniz hakkında bize bilgi verin',
    'leadForm.goalsPlaceholder': 'UK pazarına giriş için ana hedefleriniz nelerdir? Karşılaştığınız özel zorluklar var mı?',
    'leadForm.namePlaceholder': 'Adınız ve soyadınız',
    'leadForm.emailPlaceholder': 'e-posta@sirketiniz.com',
    'leadForm.phonePlaceholder': '+90 xxx xxx xxxx',
    'leadForm.companyPlaceholder': 'Şirketinizin adı',
    'leadForm.submit': 'Ücretsiz Analizimi Al',
    'leadForm.processing': 'İşleniyor...',
    'leadForm.privacy': 'Bu formu göndererek Converta\'den iletişim almayı kabul ediyorsunuz. Gizliliğinize saygı duyuyoruz ve asla spam göndermeyeceğiz.',
    'leadForm.successTitle': 'İlginiz için teşekkür ederiz!',
    'leadForm.successDesc': '24 saat içinde kişiselleştirilmiş iş içgörülerinizle sizinle iletişime geçeceğiz.',
    'leadForm.errorTitle': 'Bir şeyler yanlış gitti',
    'leadForm.errorDesc': 'Lütfen tekrar deneyin veya destek ekibimizle iletişime geçin.',
    
    // Industries
    'industry.technology': 'Teknoloji',
    'industry.manufacturing': 'İmalat',
    'industry.retail': 'Perakende ve E-ticaret',
    'industry.foodBeverage': 'Gıda ve İçecek',
    'industry.textiles': 'Tekstil ve Moda',
    'industry.healthcare': 'Sağlık',
    'industry.construction': 'İnşaat',
    'industry.automotive': 'Otomotiv',
    'industry.finance': 'Finans',
    'industry.consulting': 'Danışmanlık',
    'industry.other': 'Diğer',
    
    // Interests
    'interest.ukMarketEntry': 'UK Pazar Girişi',
    'interest.businessAnalysis': 'İş Analizi',
    'interest.partnerMatching': 'Partner Eşleştirme',
    'interest.complianceSupport': 'Uyumluluk Desteği',
    'interest.financialPlanning': 'Finansal Planlama',
    'interest.digitalMarketing': 'Dijital Pazarlama',

    // Features Page
    'features.badge': 'Kapsamlı İş Zekası Paketi',
    'features.heroTitle': 'İşinizi Büyütmek İçin',
    'features.heroTitleHighlight': 'İhtiyacınız Olan Her Araç',
    'features.heroDesc': 'AI destekli pazar analizinden partner eşleştirme ve uyumluluk takibine kadar, bilinçli iş kararları almak ve büyümeyi hızlandırmak için ihtiyacınız olan her şeyi sağlar.',
    'features.startAnalysis': 'Ücretsiz Analiz Başlat',
    'features.scheduleDemo': 'Demo Planla',
    'features.scheduling': 'Planlanıyor...',
    'features.coreTitle': 'Temel Özellikler',
    'features.coreSubtitle': 'Başarılı olmanız için ihtiyacınız olan içgörüleri ve bağlantıları sağlayan güçlü araçlar',
    'features.whyChoose': 'Neden Converta?',
    'features.whyChooseSubtitle': 'Büyüme yolculuklarında platformumuza güvenen binlerce işletmeye katılın',
    'features.ctaTitle': 'İşinizi Dönüştürmeye Hazır mısınız?',
    'features.ctaSubtitle': 'AI destekli platformumuzla büyüme potansiyellerini keşfetmiş binlerce işletmeye katılın.',
    
    // Feature Cards
    'features.aiAnalysisTitle': 'AI İş Analizi',
    'features.aiAnalysisDesc': 'İş performansınız, pazar konumunuz ve büyüme fırsatlarınız hakkında kapsamlı AI destekli analiz alın',
    'features.aiAnalysis1': 'Pazar hazırlık skorlama',
    'features.aiAnalysis2': 'Rekabet ortamı analizi',
    'features.aiAnalysis3': 'Risk değerlendirme ve azaltma',
    'features.aiAnalysis4': 'Büyüme fırsatı belirleme',
    'features.partnerNetworkTitle': 'Doğrulanmış Partner Ağı',
    'features.partnerNetworkDesc': 'İhtiyaçlarınıza özel olarak seçilmiş, önceden incelenmiş hizmet sağlayıcılar, danışmanlar ve iş ortaklarıyla bağlantı kurun',
    'features.partnerNetwork1': 'Hukuki ve muhasebe hizmetleri',
    'features.partnerNetwork2': 'Pazarlama ve tasarım ajansları',
    'features.partnerNetwork3': 'Teknoloji sağlayıcıları',
    'features.partnerNetwork4': 'Lojistik ve yerine getirme',
    'features.complianceTitle': 'Uyumluluk Takibi',
    'features.complianceDesc': 'Otomatik takip, belge oluşturma ve düzenleyici rehberlikle uyumlu kalın',
    'features.compliance1': 'Otomatik uyumluluk kontrol listeleri',
    'features.compliance2': 'Belge şablonu kütüphanesi',
    'features.compliance3': 'Düzenleyici değişiklik uyarıları',
    'features.compliance4': 'Uzman danışmanlık erişimi',
    'features.roadmapTitle': 'Akıllı Yol Haritası',
    'features.roadmapDesc': 'Net kilometre taşları ve başarı metrikleri ile kişiselleştirilmiş, eyleme dönüştürülebilir yol haritaları alın',
    'features.roadmap1': 'Hedef odaklı planlama',
    'features.roadmap2': 'İlerleme takip panosu',
    'features.roadmap3': 'Kilometre taşı bildirimleri',
    'features.roadmap4': 'Başarı metriği izleme',
    'features.analyticsTitle': 'Gerçek Zamanlı Analitik',
    'features.analyticsDesc': 'Canlı panolar ve akıllı uyarılarla iş performansınızı izleyin',
    'features.analytics1': 'Canlı performans panoları',
    'features.analytics2': 'Özel KPI takibi',
    'features.analytics3': 'Otomatik içgörüler ve uyarılar',
    'features.analytics4': 'Dışa aktarılabilir raporlar',
    'features.securityTitle': 'Kurumsal Güvenlik',
    'features.securityDesc': 'Uluslararası standartlara tam veri gizliliği ve uyumluluğu olan banka seviyesi güvenlik',
    'features.security1': 'Uçtan uca şifreleme',
    'features.security2': 'GDPR uyumluluğu',
    'features.security3': 'SOC 2 Type II sertifikalı',
    'features.security4': 'Düzenli güvenlik denetimleri',
    'features.saveTime': 'Zaman ve Kaynak Tasarrufu',
    'features.saveTimeDesc': 'Manuel araştırma ve planlamaya haftalar harcamak yerine karmaşık analizleri otomatikleştirin ve anında içgörüler alın.',
    'features.expertLevel': 'Uzman Seviyesi İçgörüler',
    'features.expertLevelDesc': 'Fortune 500 şirketlerinin aldığı kalitede analize, maliyetin ve zamanın çok küçük bir kısmıyla erişin.',
    'features.globalScale': 'Küresel Ölçeklenebilirlik',
    'features.globalScaleDesc': 'Girişimlerden kuruluşlara kadar her büyüklükteki işletme için uluslararası genişleme desteği ile inşa edilmiştir.',
    
    // Partners Page
    'partners.title': 'Partner Dizini',
    'partners.subtitle': 'Doğrulanmış UK pazar giriş partnerleriyle bağlantı kurun',
    'partners.applyPartner': 'Partner Olarak Başvur',
    'partners.back': 'Geri',
    'partners.verifiedPartners': 'Doğrulanmış Partnerler',
    'partners.readyToHelp': 'İşinize yardımcı olmaya hazır',
    'partners.serviceCategories': 'Hizmet Kategorileri',
    'partners.differentSpecializations': 'Farklı uzmanlık alanları',
    'partners.joinNetwork': 'Ağa Katıl',
    'partners.applyNow': 'Şimdi Başvur',
    'partners.signInToApply': 'Partner olarak başvurmak için giriş yapın',
    'partners.successStories': 'Başarı Hikayeleri',
    'partners.loading': 'Partnerler yükleniyor...',
    'partners.noPartners': 'Henüz doğrulanmış partner yok',
    'partners.beFirst': 'Partner ağımıza katılan ilk kişi olun ve Türk KOBİ\'lerinin UK pazarına girmesine yardımcı olun',
    'partners.applicationSubmitted': 'Başvuru Gönderildi!',
    'partners.applicationDesc': 'Partner başvurunuz inceleme için gönderildi.',
    'partners.error': 'Hata',
    'partners.failedToLoad': 'Partnerler yüklenemedi.',

    // Pricing Page
    'pricing.title': 'Fiyatlandırma Planları',
    'pricing.backToDashboard': 'Kontrol Paneline Dön',
    'pricing.manageSubscription': 'Aboneliği Yönet',
    'pricing.partnerDirectory': 'Partner Dizini',
    'pricing.customSolution': 'Özel Bir Çözüme mi İhtiyacınız Var?',
    'pricing.customDesc': 'Büyük bir organizasyonunuz varsa veya özel özelliklere ihtiyacınız varsa, ihtiyaçlarınıza özel bir çözüm tartışmak isteriz.',
    'pricing.contactSales': 'Satış İle İletişime Geçin',
    'pricing.authRequired': 'Kimlik Doğrulama Gerekli',
    'pricing.authRequiredDesc': 'Bir plana abone olmak için lütfen giriş yapın.',
    'pricing.errorTitle': 'Hata',
    'pricing.subscriptionError': 'Abonelik işlenemedi. Lütfen tekrar deneyin.',
    'pricing.manageError': 'Abonelik yönetimi açılamadı. Lütfen tekrar deneyin.',

    // Access Gate
    'accessGate.title': 'Converta MVP\'ye Hoş Geldiniz',
    'accessGate.description': 'Devam etmek için erişim kodunuzu girin',
    'accessGate.codeLabel': 'Erişim Kodu',
    'accessGate.codePlaceholder': 'Erişim kodunuzu girin',
    'accessGate.errorMessage': 'Geçersiz erişim kodu. Lütfen tekrar deneyin.',
    'accessGate.verifying': 'Doğrulanıyor...',
    'accessGate.submitButton': 'Platforma Erişin',
    'accessGate.accessIncludes': 'Erişeceğiniz içerikler:',
    'accessGate.feature1': 'Tüm platform sayfaları ve özellikler genel bakışı',
    'accessGate.feature2': 'Kapsamlı AI iş analizi aracı',
    'accessGate.feature3': 'Doğrulanmış UK partner dizini',
    'accessGate.feature4': 'Detaylı pazar hazırlık raporları',
    'accessGate.contactNote': 'Erişim koduna mı ihtiyacınız var? Converta ekibiyle iletişime geçin.',

    // Auth Page
    'auth.welcome': 'Converta\'ya Hoş Geldiniz',
    'auth.subtitle': 'UK pazar yolculuğunuza başlamak için oturum açın veya kayıt olun',
    'auth.signIn': 'Giriş Yap',
    'auth.signUp': 'Kayıt Ol',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.passwordHint': 'Şifre en az 6 karakter olmalıdır',
    'auth.signingIn': 'Giriş yapılıyor...',
    'auth.creatingAccount': 'Hesap oluşturuluyor...',
    'auth.createAccount': 'Hesap Oluştur',
    'auth.backToHome': 'Ana Sayfaya Dön',
    'auth.error': 'Hata',
    'auth.invalidCredentials': 'Geçersiz e-posta veya şifre',
    'auth.emailNotConfirmed': 'Lütfen önce e-postanızı onaylayın',
    'auth.signInFailed': 'Giriş Başarısız',
    'auth.signUpFailed': 'Kayıt Başarısız',
    'auth.userExists': 'Bu e-posta ile zaten bir hesap var',
    'auth.welcomeBack': 'Tekrar Hoş Geldiniz!',
    'auth.signInSuccess': 'Başarıyla giriş yaptınız',
    'auth.accountCreated': 'Hesap Oluşturuldu!',
    'auth.checkEmail': 'Lütfen e-postanızı onay bağlantısı için kontrol edin',
    'auth.disclaimer': 'Devam ederek Kullanım Şartlarımızı ve Gizlilik Politikamızı kabul etmiş olursunuz.',
    'auth.signOut': 'Çıkış Yap',

    // Comprehensive Analysis Form
    'compForm.title': 'Kapsamlı İş Analizi',
    'compForm.subtitle': 'AI destekli içgörüler ve partner eşleştirmesi ile tam 7 kategorili değerlendirmenizi alın',
    'compForm.step': 'Adım',
    'compForm.of': '/',
    'compForm.back': 'Geri',
    'compForm.next': 'İleri',
    'compForm.complete': 'Tamamla',
    'compForm.step1Title': 'Şirket Bilgileri',
    'compForm.step1Desc': 'İşletmeniz hakkında bilgi verin',
    'compForm.step2Title': 'Pazar ve Dijital Varlık',
    'compForm.step2Desc': 'Mevcut pazar erişiminiz hakkında bilgi verin',
    'compForm.step3Title': 'Uyumluluk ve Sertifikalar',
    'compForm.step3Desc': 'Düzenleyici konumunuzu anlamamıza yardımcı olun',
    'compForm.step4Title': 'Hedefler ve Zaman Çizelgesi',
    'compForm.step4Desc': 'Genişleme planlarınız hakkında bilgi verin',
    'compForm.companyName': 'Şirket Adı',
    'compForm.industry': 'Sektör',
    'compForm.selectIndustry': 'Sektörünüzü seçin',
    'compForm.companySize': 'Şirket Büyüklüğü',
    'compForm.selectSize': 'Şirket büyüklüğü seçin',
    'compForm.yearEstablished': 'Kuruluş Yılı',
    'compForm.websiteUrl': 'Web Sitesi URL',
    'compForm.businessDesc': 'İş Tanımı',
    'compForm.businessDescPlaceholder': 'İşletmenizin ne yaptığını, ana ürün/hizmetlerinizi ve sizi benzersiz kılan özellikleri açıklayın',
    'compForm.productsServices': 'Ürünler/Hizmetler',
    'compForm.productsPlaceholder': 'Ana ürün veya hizmetlerinizi detaylı olarak açıklayın',
    'compForm.currentMarkets': 'Mevcut Pazarlar',
    'compForm.annualRevenue': 'Yıllık Gelir',
    'compForm.selectRevenue': 'Gelir aralığı seçin',
    'compForm.digitalPresence': 'Dijital Varlık',
    'compForm.hasOnlineStore': 'Online mağazamız var',
    'compForm.hasEcommerce': 'E-ticaret platformları kullanıyoruz (Shopify, WooCommerce vb.)',
    'compForm.hasEnglishWebsite': 'Web sitemiz İngilizce olarak mevcut',
    'compForm.regulatoryCompliance': 'Düzenleyici Uyumluluk Deneyimi',
    'compForm.qualityCerts': 'Kalite Sertifikaları',
    'compForm.targetRegions': 'Hedef Genişleme Bölgeleri',
    'compForm.businessGoals': 'İş Hedefleri',
    'compForm.goalsPlaceholder': 'İş genişlemesi için ana hedefleriniz neler? Ne elde etmeyi umuyorsunuz?',
    'compForm.timeline': 'Genişleme Zaman Çizelgesi',
    'compForm.selectTimeline': 'Zaman çizelgenizi seçin',
    'compForm.budget': 'Yatırım Bütçesi',
    'compForm.selectBudget': 'Bütçe aralığı seçin',
    'compForm.submitted': 'Bilgiler Gönderildi!',
    'compForm.processing': 'Kapsamlı analiziniz işleniyor...',
    'compForm.companyNamePlaceholder': 'Şirket adınızı girin',
    'compForm.websitePlaceholder': 'https://www.sirketiniz.com',
    'compForm.yearPlaceholder': '2020',
    // Industry options
    'compForm.industryTechnology': 'Teknoloji',
    'compForm.industryHealthcare': 'Sağlık',
    'compForm.industryRetail': 'Perakende',
    'compForm.industryManufacturing': 'İmalat',
    'compForm.industryServices': 'Hizmetler',
    'compForm.industryFoodBeverage': 'Gıda ve İçecek',
    'compForm.industryConstruction': 'İnşaat',
    'compForm.industryAutomotive': 'Otomotiv',
    'compForm.industryOther': 'Diğer',
    // Company size options
    'compForm.size1to10': '1-10 çalışan',
    'compForm.size11to50': '11-50 çalışan',
    'compForm.size51to200': '51-200 çalışan',
    'compForm.size200plus': '200+ çalışan',
    // Revenue options
    'compForm.revenue0to50k': '$0 - $50k',
    'compForm.revenue50to250k': '$50k - $250k',
    'compForm.revenue250to1m': '$250k - $1M',
    'compForm.revenue1to5m': '$1M - $5M',
    'compForm.revenue5mplus': '$5M+',
    // Market options
    'compForm.marketDomestic': 'Yurt İçi',
    'compForm.marketEurope': 'Avrupa',
    'compForm.marketNorthAmerica': 'Kuzey Amerika',
    'compForm.marketAsia': 'Asya',
    'compForm.marketMiddleEast': 'Orta Doğu',
    'compForm.marketOther': 'Diğer',
    // Digital presence options
    'compForm.digitalWebsite': 'Web Sitesi',
    'compForm.digitalSocialMedia': 'Sosyal Medya',
    'compForm.digitalEcommerce': 'E-ticaret',
    'compForm.digitalMobileApp': 'Mobil Uygulama',
    'compForm.digitalEmailMarketing': 'E-posta Pazarlama',
    'compForm.digitalAdvertising': 'Dijital Reklamcılık',
    // Compliance options
    'compForm.complianceISO': 'ISO Standartları',
    'compForm.complianceCE': 'CE İşareti',
    'compForm.complianceFDA': 'FDA Onayı',
    'compForm.complianceGDPR': 'GDPR Uyumluluğu',
    'compForm.complianceExport': 'İhracat Lisansı',
    'compForm.complianceQuality': 'Kalite Sistemleri',
    // Certification options
    'compForm.certISO9001': 'ISO 9001',
    'compForm.certISO14001': 'ISO 14001',
    'compForm.certOHSAS': 'OHSAS 18001',
    'compForm.certOrganic': 'Organik Sertifika',
    'compForm.certFairTrade': 'Adil Ticaret',
    'compForm.certIndustry': 'Sektöre Özel',
    // Region options
    'compForm.regionUK': 'İngiltere',
    'compForm.regionEurope': 'Avrupa',
    'compForm.regionNorthAmerica': 'Kuzey Amerika',
    'compForm.regionAsiaPacific': 'Asya Pasifik',
    'compForm.regionMiddleEast': 'Orta Doğu',
    'compForm.regionGlobal': 'Küresel',
    // Timeline options
    'compForm.timeline3to6': '3-6 ay',
    'compForm.timeline6to12': '6-12 ay',
    'compForm.timeline1to2': '1-2 yıl',
    'compForm.timeline2plus': '2+ yıl',
    // Budget options
    'compForm.budget0to10k': '$0 - $10k',
    'compForm.budget10to50k': '$10k - $50k',
    'compForm.budget50to100k': '$50k - $100k',
    'compForm.budget100kplus': '$100k+',

    // Comprehensive Analysis Results
    'compResults.title': 'Kapsamlı İş Analizi',
    'compResults.loading': 'Kapsamlı Analiziniz İşleniyor',
    'compResults.loadingDesc': 'Bu 30-60 saniye sürebilir...',
    'compResults.failed': 'Analiz Başarısız',
    'compResults.failedDesc': 'Kapsamlı analizinizi işleyemedik. Lütfen tekrar deneyin.',
    'compResults.noData': 'İş Verisi Yok',
    'compResults.noDataDesc': 'Lütfen önce kapsamlı analiz formunu doldurun.',
    'compResults.returnHome': 'Ana Sayfaya Dön',
    'compResults.exportReport': 'Raporu Dışa Aktar',
    'compResults.backHome': 'Ana Sayfaya Dön',
    'compResults.ukReadiness': 'İngiltere Pazar Hazırlığı',
    'compResults.confidenceHigh': 'YÜKSEK',
    'compResults.confidenceMedium': 'ORTA',
    'compResults.confidenceLow': 'DÜŞÜK',
    'compResults.dataCompleteness': 'Veri Tamlığı',
    'compResults.fieldsIncomplete': 'alan eksik',
    'compResults.companiesHouseVerified': 'Companies House Doğrulandı',
    'compResults.completedSections': 'Tamamlanan bölümler:',
    'compResults.dataSources': 'Veri kaynakları:',
    'compResults.about': 'Hakkında',
    'compResults.specialties': 'Uzmanlık Alanları',
    'compResults.contactInfo': 'İletişim Bilgileri',
    'compResults.email': 'E-posta',
    'compResults.phone': 'Telefon',
    'compResults.website': 'Web Sitesi',
    'compResults.location': 'Konum',
    'compResults.noContactInfo': 'İletişim bilgisi mevcut değil',
    'compResults.sendEmail': 'E-posta Gönder',
    'compResults.close': 'Kapat',
    'compResults.contactPartner': 'Partner ile İletişim',
    'compResults.scoreBreakdown': 'Puan Dağılımı',
    'compResults.recommendations': 'Öneriler',
    'compResults.immediate': 'Acil',
    'compResults.shortTerm': 'Kısa Vadeli',
    'compResults.longTerm': 'Uzun Vadeli',
    'compResults.compliance': 'Uyumluluk Değerlendirmesi',
    'compResults.criticalReq': 'Kritik Gereksinimler',
    'compResults.riskAreas': 'Risk Alanları',
    'compResults.partners': 'Partner Önerileri',
    'compResults.urgency': 'Aciliyet',
    'compResults.high': 'Yüksek',
    'compResults.medium': 'Orta',
    'compResults.low': 'Düşük',
    'compResults.disclaimer': 'Bu analiz AI tarafından oluşturulmuştur ve yalnızca bilgilendirme amaçlıdır. Yasal, mali veya profesyonel tavsiye niteliği taşımaz.',
    'compResults.methodology': 'Analiz Metodolojisi ve Veri Kalitesi',
    'compResults.methodologyDesc': 'Puanınızın nasıl hesaplandığını ve kullanılan veri kaynaklarını anlayın',
    'compResults.confidenceLevel': 'Güven Seviyesi',
    'compResults.verificationStatus': 'Doğrulama Durumu',
    'compResults.verified': 'DOĞRULANDI',
    'compResults.unverified': 'DOĞRULANMADI',
    'compResults.verifiedVia': 'Şirket Companies House API ile doğrulandı',
    'compResults.notVerified': 'Şirket doğrulanmadı - UK kaydı önerilir',
    'compResults.scoringMethod': 'Puanlama Metodolojisi',
    'compResults.dataSourcesUsed': 'Kullanılan Veri Kaynakları:',
    'compResults.improveAccuracy': 'Analiz Doğruluğunu Artırın',
    'compResults.provideMore': 'Veri tamlığını ve güveni artırmak için ek bilgi sağlayın:',
    'compResults.expertRecommended': 'Uzman İncelemesi Önerilir',
    'compResults.getExpertReview': 'Uzman İncelemesi Al',
    'compResults.requestExpert': 'Uzman İncelemesi Talep Et',
    'compResults.shareResults': 'Sonuçları Paylaş',
    'compResults.viewProgress': 'İlerleme Geçmişini Görüntüle',
    'compResults.overview': 'Genel Bakış',
    'compResults.insights': 'İçgörüler',
    'compResults.roadmap': 'Yol Haritası',
    'compResults.detailedBreakdown': 'Detaylı Puan Dağılımı',
    'compResults.categoriesAnalyzed': 'Analiz Edilen Kategoriler',
    'compResults.evidenceBased': 'Özel puanlama algoritmaları kullanılarak kanıta dayalı analiz',
    'compResults.highReadiness': 'Yüksek Hazırlık',
    'compResults.moderateReadiness': 'Orta Hazırlık',
    'compResults.needsDevelopment': 'Geliştirme Gerekli',

    // Score Categories
    'scoreCategory.productMarketFit': 'Ürün-Pazar Uyumu',
    'scoreCategory.productMarketFitDesc': 'İngiltere pazar talebi ve rekabet analizi',
    'scoreCategory.regulatoryCompatibility': 'Düzenleyici Uyumluluk',
    'scoreCategory.regulatoryCompatibilityDesc': 'İngiltere uyumluluk ve yasal gereksinimler',
    'scoreCategory.digitalReadiness': 'Dijital Hazırlık',
    'scoreCategory.digitalReadinessDesc': 'Online varlık ve e-ticaret kapasitesi',
    'scoreCategory.logisticsPotential': 'Lojistik Potansiyeli',
    'scoreCategory.logisticsPotentialDesc': 'Tedarik zinciri ve yerine getirme hazırlığı',
    'scoreCategory.scalabilityAutomation': 'Ölçeklenebilirlik ve Otomasyon',
    'scoreCategory.scalabilityAutomationDesc': 'Büyüme potansiyeli ve operasyonel verimlilik',
    'scoreCategory.founderTeamStrength': 'Kurucu/Ekip Gücü',
    'scoreCategory.founderTeamStrengthDesc': 'Deneyim ve İngiltere pazar bilgisi',
    'scoreCategory.investmentReadiness': 'Yatırım Hazırlığı',
    'scoreCategory.investmentReadinessDesc': 'İngiltere genişlemesi için finansal hazırlık',

    // Admin Page
    'admin.title': 'Yönetici Paneli',
    'admin.subtitle': 'Converta Yönetim Konsolu',
    'admin.backToSite': 'Siteye Dön',
    'admin.systemHealth': 'Sistem Durumu',
    'admin.overview': 'Genel Bakış',
    'admin.analytics': 'Analitik',
    'admin.users': 'Kullanıcılar',
    'admin.partners': 'Ortaklar',
    'admin.performance': 'Performans',
    'admin.marketing': 'Pazarlama',
    'admin.totalUsers': 'Toplam Kullanıcılar',
    'admin.activeUsers': 'Aktif Kullanıcılar',
    'admin.pendingPartners': 'Bekleyen Ortaklar',
    'admin.conversionRate': 'Dönüşüm Oranı',
    'admin.quickActions': 'Hızlı İşlemler',
    'admin.quickActionsDesc': 'Yaygın yönetim görevleri ve kısayollar',
    'admin.reviewPartners': 'Ortakları İncele',
    'admin.applicationsPending': 'başvuru beklemede',
    'admin.userManagement': 'Kullanıcı Yönetimi',
    'admin.manageAccounts': 'Kullanıcı hesaplarını ve etkinliği yönetin',
    'admin.viewAnalytics': 'Analitik Görüntüle',
    'admin.platformInsights': 'Platform performans içgörüleri',
    'admin.recentActivity': 'Son Etkinlik',
    'admin.recentActivityDesc': 'En son platform olayları ve kullanıcı etkileşimleri',
    'admin.loading': 'Yükleniyor...',
    'admin.verifyingAccess': 'Erişim doğrulanıyor...',
    'admin.authRequired': 'Kimlik Doğrulama Gerekli',
    'admin.authRequiredDesc': 'Yönetici paneline erişmek için lütfen giriş yapın.',
    'admin.accessDenied': 'Erişim Reddedildi',
    'admin.accessDeniedDesc': 'Bu sayfaya erişim izniniz yok.',
    'admin.aboveAverage': 'Sektör ortalamasının üzerinde',
    'admin.fromLastMonth': 'geçen aya göre',
    'admin.activeRate': 'aktif oran',
    'admin.totalAnalyses': 'Toplam Analizler',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};