// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qafetzoqccqafbbspjcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZmV0em9xY2NxYWZiYnNwamNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTM0MzIsImV4cCI6MjA2NzcyOTQzMn0.uUv8k7_dKR8A1SyrsUZqYSdZG0uWHYzHCw32cfmczfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});